# syntax=docker/dockerfile:1.7-labs
FROM ruby:3.3-slim

ARG UID="11112"

# https://techoverflow.net/2021/01/13/how-to-use-apt-install-correctly-in-your-dockerfile/
ENV DEBIAN_FRONTEND=noninteractive 
RUN apt-get update -qq \
    && apt-get install -y --no-install-recommends \
    build-essential libpq-dev postgresql-client \
    curl libvips42 nodejs npm ncdu \
    && rm -rf /var/lib/apt/lists/*

# create app directory and create custom user with uid > 10000 to run the app in it
WORKDIR /collectif-objets
RUN useradd -s /bin/bash -u "${UID}" -d /collectif-objets co && chown "${UID}":"${UID}" /collectif-objets
USER "${UID}"

# install ruby and npm libraries
COPY --chown="${UID}":"${UID}" Gemfile Gemfile.lock package.json package-lock.json /collectif-objets/
RUN bundle install && npm install

# copy only necessary application files
COPY --chown="${UID}":"${UID}" --parents=true app bin cms config contenus db lib scripts public /collectif-objets/
COPY --chown="${UID}":"${UID}" --parents=true config.ru spec storage tmp vendor prawn_assets /collectif-objets/

EXPOSE 3000

CMD ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
