apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: collectif-objets
    app.kubernetes.io/instance: collectif-objets-dev1
    app.kubernetes.io/component: web
  name: web
spec:
  ports:
    - name: "web-ror"
      port: 3000
      targetPort: 3000
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: collectif-objets
    app.kubernetes.io/instance: collectif-objets-dev1
    app.kubernetes.io/component: web
