require:
  - rubocop-rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "shared/db/**/*"
    - "config/db/*"
    - "config/environments/*"
    - "config/initializers/*"
    - "lib/tasks/**/*"
    - ".irbrc"
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*
    - app/lib/demos/**/*
    - lib/mailer_previews/**/*
    - app/components/**/*_preview.rb

Style/ClassAndModuleChildren:
  Exclude:
    - app/components/**/*_preview.rb
