require:
  - rubocop-rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "shared/db/**/*"
    - "config/db/*"
    - "config/environments/*"
    - "config/initializers/*"
    - "lib/tasks/**/*"
    - ".irbrc"
    - "spec/rails_helper.rb"

  SuggestExtensions: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/concerns/*.rb

Style/Lambda:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

# Disable because where and exists? don't accept the same arguments
Rails/WhereExists:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - app/components/**/*_preview.rb

# voluntarily disable Length based cops as they provide little value

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

# we use method names like merimee_REF in the synchronizer
Naming/MethodName:
  Exclude:
    - app/jobs/synchronizer/**/*

# we use parameter names like merimee_REF in the synchronizer
Naming/MethodParameterName:
  Exclude:
    - app/jobs/synchronizer/**/*

# we use variable names like merimee_REF in the synchronizer
Naming/VariableName:
  Exclude:
    - app/jobs/synchronizer/**/*
