# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.1"

gem "activerecord_where_assoc"
gem "aws-sdk-s3", require: false
gem "bootsnap", require: false
gem "devise", "~> 4.8"
gem "devise-i18n", "~> 1.10"
gem "importmap-rails"
gem "pagy", "~> 5.10"
gem "pg", "~> 1.3"
gem "puma", "~> 5.6"
gem "rails", "~> 7.0.1"
gem "sentry-rails", "~> 5.1"
gem "sentry-ruby", "~> 5.1"
gem "sib-api-v3-sdk"
gem "sidekiq"
gem "sprockets-rails"
gem "stimulus-rails"
gem "turbo-rails"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "factory_bot_rails"
  gem "rspec-rails", "~> 5.1"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
end

group :development do
  gem "htmlbeautifier"
  gem "pry"
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
