# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

gem "aasm"
gem "actioncable"
gem "active_model_validates_intersection_of"
gem "activerecord_where_assoc"
gem "after_commit_everywhere"
gem "aws-sdk-s3", require: false
gem "bootsnap", require: false
gem "devise", "~> 4.8"
gem "devise-i18n", "~> 1.10"
gem "image_processing"
gem "importmap-rails"
gem "lookbook"
gem "matrix"
gem "pagy", "~> 5.10"
gem "pg", "~> 1.3"
gem "pg_search"
gem "prawn"
gem "prawn-table"
gem "puma", "~> 5.6"
gem "rails", "~> 7.0.1"
gem "sentry-rails"
gem "sentry-ruby"
gem "sentry-sidekiq"
gem "sib-api-v3-sdk"
gem "sidekiq"
gem "sprockets-rails"
gem "stimulus-rails"
gem "turbo-rails"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
gem "view_component"

group :development, :test do
  gem "cypress-rails"
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "factory_bot_rails"
  gem "launchy"
  gem "rspec-rails", "~> 5.1"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
end

group :development do
  gem "htmlbeautifier"
  gem "progressbar"
  gem "pry"
  gem "rubocop-daemon", require: false
  gem "web-console"
end
