test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

scaleway_defaults: &scaleway_defaults
  service: S3
  endpoint: https://s3.fr-par.scw.cloud
  region: fr-par

mc_ovh_defaults: &mc_ovh_defaults
  endpoint: https://s3.gra.io.cloud.ovh.net
  service: S3
  region: gra
  # force_path_style: true # Critical for OVH S3 compatibility LOL

mc_ovh_staging: &mc_ovh_staging
  !!merge <<: *mc_ovh_defaults
  access_key_id: <%= ENV["BUCKET_USER_ACCESS_KEY_ID"] %>
  #access_key_id: <%= Rails.application.credentials.dig(:mc_ovh_s3, :user_dev_colle, :access_key_id) %>
  secret_access_key: <%= ENV["BUCKET_USER_SECRET_ACCESS_KEY"] %>
  #secret_access_key: <%= Rails.application.credentials.dig(:mc_ovh_s3, :user_dev_colle, :secret_access_key) %>
  bucket: <%= ENV["BUCKET_NAME"] %>

mc_ovh_prod: &mc_ovh_prod
  !!merge <<: *mc_ovh_defaults
  access_key_id: <%= ENV["BUCKET_USER_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["BUCKET_USER_SECRET_ACCESS_KEY"] %>
  bucket: <%= ENV["BUCKET_NAME"] %>

scaleway_development:
  !!merge <<: *scaleway_defaults
  access_key_id: <%= Rails.application.credentials.dig(:scaleway, :project_co, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:scaleway, :project_co, :secret_access_key) %>
  bucket: collectif-objets-development2

scaleway_staging:
  !!merge <<: *scaleway_defaults
  access_key_id: <%= Rails.application.credentials.dig(:scaleway, :project_co, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:scaleway, :project_co, :secret_access_key) %>
  bucket: collectif-objets-staging2

scaleway_production: &scaleway_production
  !!merge <<: *scaleway_defaults
  access_key_id: <%= Rails.application.credentials.dig(:scaleway, :project_default, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:scaleway, :project_default, :secret_access_key) %>
  bucket: collectif-objets-production

# scaleway name needs to be preserved for prod because attachments were saved in prod db with this service name
scaleway:
  !!merge <<: *mc_ovh_prod
  # !!merge <<: *scaleway_production

# same problem for migration to OVH since we use refs to scaleway_staging in staging database
scaleway_staging:
  !!merge <<: *mc_ovh_staging
