source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.1"

gem "rails", "~> 7.0.2", ">= 7.0.2.3"
gem "sprockets-rails"
gem "pg", "~> 1.1"
gem "puma", "~> 5.6"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "bootsnap", require: false
gem "sassc-rails"
gem "devise", "~> 4.8"
gem "activeadmin", "~> 2.11"
gem 'devise-i18n'
gem "draper", "~> 4.0"
gem "aws-sdk-s3", require: false
gem "sidekiq"
gem "pg_search"
gem "active_model_validates_intersection_of"
gem "aasm"
gem "after_commit_everywhere"

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem "web-console"
end
