TRUNCATE TABLE active_admin_comments,
active_storage_blobs,
active_storage_attachments,
active_storage_variant_records,
admin_users,
campaign_emails,
campaign_recipients,
campaigns,
recensements,
dossiers,
objets,
users,
edifices,
communes,
conservateur_roles,
conservateurs,
departements,
objet_overrides;
