apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: collectif-objets
    app.kubernetes.io/instance: collectif-objets-dev1
    app.kubernetes.io/component: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: collectif-objets
      app.kubernetes.io/instance: collectif-objets-dev1
      app.kubernetes.io/component: db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: collectif-objets
        app.kubernetes.io/instance: collectif-objets-dev1
        app.kubernetes.io/component: db
    spec:
      containers:
      - name: posgres-dev
        env:
        - name: POSTGRES_PASSWORD
          value: objets
        image: postgres:14
      restartPolicy: Always

