apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: collectif-objets
    app.kubernetes.io/instance: collectif-objets-dev1
    app.kubernetes.io/component: db
  name: db
spec:
  ports:
    - name: "postgres"
      port: 5432
      targetPort: 5432
  type: ClusterIP
  selector:
    app.kubernetes.io/name: collectif-objets
    app.kubernetes.io/instance: collectif-objets-dev1
    app.kubernetes.io/component: db
